# Generated by Django 4.0.6 on 2022-09-17 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=250, verbose_name='nom')),
                ('prenom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=250)),
                ('groupe', models.CharField(max_length=3)),
                ('permanent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'don',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDeDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('coordonnee', models.CharField(max_length=250)),
                ('information', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='site')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='hopital')),
                ('Aplus', models.BooleanField(default=False)),
                ('Amoins', models.BooleanField(default=False)),
                ('Bplus', models.BooleanField(default=False)),
                ('Bmoins', models.BooleanField(default=False)),
                ('Oplus', models.BooleanField(default=False)),
                ('Omoins', models.BooleanField(default=False)),
                ('ABplus', models.BooleanField(default=False)),
                ('ABmoins', models.BooleanField(default=False)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(max_length=250)),
                ('commentaire', models.TextField()),
                ('membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.commune'),
        ),
    ]
