# Generated by Django 4.0.6 on 2022-09-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'verbose_name': 'membre'},
        ),
        migrations.AlterModelOptions(
            name='sitededon',
            options={'verbose_name': 'site'},
        ),
    ]
