# Generated by Django 4.0.6 on 2022-09-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_membre_options_alter_sitededon_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitededon',
            name='information',
        ),
        migrations.AlterField(
            model_name='sitededon',
            name='coordonnee',
            field=models.CharField(max_length=1000),
        ),
    ]
