# Generated by Django 4.0.6 on 2022-09-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_sitededon_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hopital'),
        ),
        migrations.AlterField(
            model_name='sitededon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site'),
        ),
    ]
