# Generated by Django 4.0.6 on 2022-09-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_hopital_image_alter_sitededon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={},
        ),
    ]
