# Generated by Django 4.0.6 on 2022-09-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_membre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'verbose_name': 'membre'},
        ),
    ]
