# Generated by Django 4.0.6 on 2022-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_membre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'commune'},
        ),
        migrations.AlterField(
            model_name='membre',
            name='groupe',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
