# Generated by Django 4.0.6 on 2022-09-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_commune_options_alter_membre_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='admins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='hopital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.hopital'),
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
    ]
